name = "cipherhacks-website"
compatibility_date = "2025-08-13"

main = "src/functions/index.ts"

routes = [
  { pattern = "cipherhacks.tech/*", zone_name = "cipherhacks.tech" }
]

[assets]
directory = "./build"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = true

[alias]
"@mirageshield/mirage" = "@mirageshield/mirage/dist/index.mjs"
